#! /usr/bin/env python3
import multiprocessing
import os
import sys

import chassis
from colored import commandInfo, debugInfo, detectedInfo, info, logoInfo


def sh(command):
    os.system(command)


def run():
    sh('python mihotel_rover.py')


def config():
    if os.path.exists(os.path.expanduser('~/Desktop/opencv_contrib_python-4.1.0.25-cp37-cp37m-linux_armv7l.whl')):
        sh('config/install.sh')
        info('Done!')
    else:
        info('Must have opencv-contrib-python wheel in ~/Desktop. See config/README.md for help.')


commands = {
    'default': run,
    'config': config,
}

# change cwd first
os.chdir(sys.path[0])
commands[sys.argv[1] if len(sys.argv) > 1 else 'default']()
